# Generated by Django 5.0.1 on 2024-01-21 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoationCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LocationOblast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_oblast', models.CharField(max_length=255)),
                ('id_conutry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.loationcountry')),
            ],
        ),
        migrations.CreateModel(
            name='LocationRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_region', models.CharField(max_length=255)),
                ('id_oblast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.locationoblast')),
            ],
        ),
        migrations.CreateModel(
            name='LocationOkmot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_okmot', models.CharField(max_length=255)),
                ('id_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.locationregion')),
            ],
        ),
        migrations.CreateModel(
            name='LocationVillage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_village', models.CharField(max_length=255, verbose_name='Айыл')),
                ('id_okmot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.locationokmot', verbose_name='Айыл окмот')),
            ],
        ),
    ]
