# Generated by Django 5.0.1 on 2024-01-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reklama', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reklama',
            name='date_create',
            field=models.DateTimeField(),
        ),
    ]
