# Generated by Django 5.0.1 on 2024-01-21 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCharba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_charba', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Charba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('code_chars', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255, null=True)),
                ('date_register', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type_charba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charbamodel.typecharba')),
            ],
        ),
        migrations.CreateModel(
            name='CharbaUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_update', models.DateTimeField(auto_now_add=True)),
                ('charba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charbamodel.charba')),
                ('mew_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
