# Generated by Django 5.0.1 on 2024-01-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charbamodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charbaupdate',
            name='date_update',
            field=models.DateTimeField(),
        ),
    ]
