# Generated by Django 5.0.1 on 2024-01-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suvaichy',
            name='user',
        ),
        migrations.AddField(
            model_name='suvaichy',
            name='suvaichy',
            field=models.CharField(default=32, max_length=255),
            preserve_default=False,
        ),
    ]
