# Generated by Django 5.0.1 on 2024-01-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suvai', '0002_remove_suvaichy_user_suvaichy_suvaichy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suvai',
            name='date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='suvai',
            name='date_start',
            field=models.DateField(),
        ),
    ]
